### ISSUE TITLE
Modifications for a NGA Model 4P

### ISSUE THREAD

**Issue by tuctboh** [mrthreeplates/TRS-80_floppy_remapper#1]
Hi,

Couldn't find a way to contact you otherwise, apologies for going this route.

I would like to add one to a Non-gate-array Model 4P, but I'm not really a hardware person. Between your not actually putting it on a 4P NGA and my unfamiliarity I was wondering if we might be able to work something out to ensure that this is workable first time around. 

Thanks, Tuc

**Comment by mrthreeplates** [comment]
Hi Tuc,

Thanks for your interest.  I'm afraid I cannot provide any support other
than what I've shared on GitHub.

The project is for diy people, but you might start a thread on vcfed
forums, or just ping the thread I already have on the remapper to see if
anyone can help you.  Perhaps there are others interested as well.  You
also need to get the board made

Best regards,

George

**Comment by tuctboh** [comment]
Hi,

Ok, thanks. I was hoping we could have an mutually acceptable arrangement, something like sending you the 4P, getting board sent to you, same with the BOM items, and compensating for your time/effort to verify and validate your understanding of what the 4P NGA is like. You'd be able to update the documentation and have a more definitive answer about the compatibility/wiring, I'd have a usable system.

If you're still not interested, that's fine, I appreciate your reply and suggestions. :)

Tuc

**Comment by mrthreeplates** [comment]
Thanks, I would like to help but just don't have the time.

If you can drum up interest, you might be able to get one of several trs80
enthusiasts to produce the board or maybe install it too.  This is probably
a long shot.  Or find someone local to help.

Or just try it yourself, it will be an adventure!

All the best, and have fun.

**Comment by tuctboh** [comment]
No worries, thanks so much!
